
GET http://localhost:5090/v1

###

GET http://localhost:5090/v1/api/categories
# GET http://localhost:5090/v1/api/categories?searchValue=apple



###



GET http://localhost:5090/v1/api/categories/36659935-2402-412d-817c-1a7770a38080



###

POST http://localhost:5090/v1/api/categories
Content-Type: application/json

{
    "name" : "smart phone",
    "description":"smart phone is the best phone"
}




###


PUT  http://localhost:5090/v1/api/categories/b15c6327-587f-4bb9-8d35-e9fba07f899c
Content-Type: application/json

{
    "name":"apple phonedddddd",
    "description":"aadddddddddddddddddddddddd"
}

###

DELETE  http://localhost:5090/v1/api/categories/b15c6327-587f-4bb9-8d35-e9fba07f899c

