
GET http://localhost:5090/v1

###

GET http://localhost:5090/v1/api/categories
# GET http://localhost:5090/v1/api/categories?searchValue=apple



###



GET http://localhost:5090/v1/api/categories/ca479a63-7a26-4a89-8ff6-12021af705fa



###

POST http://localhost:5090/v1/api/categories
Content-Type: application/json

{
    "name" : "",
    "description" : "gdsgsdgsdgdsgdsgs"
}




###


PUT  http://localhost:5090/v1/api/categories/0ddfc992-eefa-4953-aef9-8555d7b57097
Content-Type: application/json

{
    "name":"apple phone",
    "description":"aa"
}

###

DELETE  http://localhost:5090/v1/api/categories/afc82700-42f2-4549-a210-06d019237e26

